# Pulls current TCGplayer prices from TCGCSV (https://tcgcsv.com) for every set in
# data/sets.json and writes js/data.js for the site.
#
#   ./scripts/update-prices.ps1                   update js/data.js
#   ./scripts/update-prices.ps1 -ListSealed 24269 list sealed products for a set, to fill in productIds
#
# Runs on Windows PowerShell 5.1 and PowerShell 7 (the GitHub Action uses 7).

param([int]$ListSealed)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$base = 'https://tcgcsv.com/tcgplayer/3' # 3 = Pokemon

function Get-Json($url) {
  # Decode as UTF-8 explicitly so accented names (Pokemon, Flabebe) survive on PowerShell 5.1.
  $response = Invoke-WebRequest $url -UseBasicParsing
  $text = [Text.Encoding]::UTF8.GetString($response.RawContentStream.ToArray())
  ($text | ConvertFrom-Json).results
}

function Get-Rarity($product) {
  ($product.extendedData | Where-Object name -eq 'Rarity').value
}

if ($ListSealed) {
  Get-Json "$base/$ListSealed/products" |
    Where-Object { -not (Get-Rarity $_) } |
    Sort-Object name |
    Format-Table productId, name -AutoSize
  return
}

$config = Get-Content (Join-Path $root 'data/sets.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$sets = @()

foreach ($set in $config.sets) {
  Write-Host "Updating $($set.name)..."
  $products = Get-Json "$base/$($set.groupId)/products"
  $prices = Get-Json "$base/$($set.groupId)/prices"

  # Market price per product. Cards prefer the Holofoil printing; sealed items only have Normal.
  $priceById = @{}
  foreach ($p in $prices) {
    if ($null -eq $p.marketPrice) { continue }
    $existing = $priceById[$p.productId]
    if ($p.subTypeName -eq 'Holofoil' -or -not $existing) {
      $priceById[$p.productId] = [double]$p.marketPrice
    }
  }

  $rarities = @()
  foreach ($rate in $set.pullRates.PSObject.Properties) {
    $cards = @(
      $products |
        Where-Object { (Get-Rarity $_) -eq $rate.Name -and $priceById.ContainsKey($_.productId) } |
        ForEach-Object { [ordered]@{ name = $_.name; productId = $_.productId; price = $priceById[$_.productId] } } |
        Sort-Object { $_.price } -Descending
    )
    if ($cards.Count -eq 0) { throw "$($set.name): no priced cards found for rarity '$($rate.Name)'" }

    $avg = ($cards | ForEach-Object { $_.price } | Measure-Object -Average).Average
    $rarities += [ordered]@{
      name = $rate.Name
      perPack = 1 / [double]$rate.Value
      avgValue = [math]::Round($avg, 2)
      cards = $cards
    }
  }

  $sealed = @()
  foreach ($item in $set.products) {
    if (-not $priceById.ContainsKey($item.productId)) {
      Write-Warning "$($set.name) $($item.name): no market price, skipping"
      continue
    }
    $sealed += [ordered]@{
      id = $item.id
      name = $item.name
      packs = $item.packs
      productId = $item.productId
      price = $priceById[$item.productId]
    }
  }

  $sets += [ordered]@{
    id = $set.id
    name = $set.name
    series = $set.series
    year = $set.year
    note = $set.note
    bulkValuePerPack = $set.bulkValuePerPack
    rarities = $rarities
    products = $sealed
  }
}

$data = [ordered]@{
  updatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
  source = 'TCGplayer market prices via TCGCSV'
  sets = $sets
}

$js = "// GENERATED by scripts/update-prices.ps1 - do not edit by hand. Edit data/sets.json instead.`n" +
      "window.RIP_DATA = " + ($data | ConvertTo-Json -Depth 10 -Compress) + ";`n"
[IO.File]::WriteAllText((Join-Path $root 'js/data.js'), $js, [Text.UTF8Encoding]::new($false))
Write-Host "Wrote js/data.js ($($sets.Count) sets)"
